### PR TITLE
More function definitions and documentation

### PR DESCRIPTION
**Pull request by tong**
Also moved the Run class out of src directory, otherwise it shows up in autocompletion when using the externs.

### CODE REVIEW

**Comment by ianharrigan** [comment]
nice one... lots of blanks filled in! 👍

**Comment by tong** [comment]
I think src/ast2obj/* and src/helpers/* should also get moved out of the src/ directory as they aren't intended to get used directly.

**Comment by ianharrigan** [comment]
But i think they'll need to be in the class path though wont they?

**Comment by tong** [comment]
Not if you call the macro in extraParams.hxml

**Comment by ianharrigan** [comment]
Ok, nice didnt know that.

**Comment by tong** [comment]
I mean you can specify a cp in extraParams.hxml (nothing special about this hxml).

**Comment by tong** [comment]
My remarks make no sense since it would be in the classpath again.
Now i am confused.

**Pull request merged**
